codestates-seb/seb45_main_031

server/routine/src/main/java/com/seb45_main_031/routine/audit/Auditable.java
server/routine/src/main/java/com/seb45_main_031/routine/dto/MultiResponseDto.java
server/routine/src/main/java/com/seb45_main_031/routine/dto/PageInfo.java
server/routine/src/main/java/com/seb45_main_031/routine/dto/SingeResponseDto.java
server/routine/src/main/java/com/seb45_main_031/routine/utils/UriCreator.java

Uri Creator
Response Dto
Audit
Issues : #24

[BE] Feat : BE 공통 유틸 기능

---

server/routine/src/main/java/com/seb45_main_031/routine/RoutineApplication.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/BusinessLogicException.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/ErrorResponse.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/GlobalExceptionHandle.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java

유효성 예외
파라미터 예외
비지니스 로직 예외
issues : #20

[BE] Feat : 공통 예외 처리

---

server/routine/src/main/java/com/seb45_main_031/routine/dto/SingeResponseDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java

Feed CRUD 기능 구현 완료입니다.
- Entity
- Dto
- Controller
- Repository
- Service
- Mapper
_+ 공통 기능 소소한 오타가 수정되었습니다. (SingleRepsonseDto)_
Issues : #16

[BE] Feat : Feed(Community) CRUD 기능 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/CommentController.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/mapper/CommentMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/repository/CommentRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/service/CommentService.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java

Comment CRUD 기능 구현 완료입니다.
Entity
Dto
Controller
Repository
Service
Mapper
+ Feed 엔티티 자료형 long -> Long 변경
+ FeedMapper 에서 Comment 추가

[BE] Feat : Comment CRUD 기능 구현

---

FE/.eslintrc.json

- .eslintrc.json에 코드를 추가하였습니다.
Issues : #33

[FE] Fix : prettier 에러 해결 코드 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

1. Add Todo Count
2. Add Complete Count 
Issues : #32

[BE] Feat: Todo Count 기능 구현

---

FE/src/App.js
FE/src/pages/TodoEditPage.js

- 타이틀, Tip box 뷰를 구현하였습니다.
- 할 일 이름, 태그 Input box 구현하였습니다.
- Emoji 입력창과 모달창을 구현하였습니다.
- 취소, 등록 버튼을 구현하였습니다.
- 취소 버튼 클릭 시 할 일 목록 페이지로 이동합니다.
Issues : #8

[FE] Feat : 할 일 작성 페이지 뷰 및 기능 일부 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java

todoResponse -> todoResponses 로 수정
Issues : #42

[BE] Rename : Responses 변수명 단순 수정

---

FE/.eslintrc.json
FE/src/App.js
FE/src/pages/todoPage.js

- 일일 달성률에 따른 달성률 게이지가 상승 또는 하락합니다.
추가로 커뮤니티 페이지에 관한 app.js 변동이 있습니다. 작업하실 때 해당 부분 지우거나 주석처리 한 후 작업 부탁드립니다 ㅠㅠ
머지 상황으로 커밋이 꼬여 죄송합니다!
Issues : #6

[FE] 할 일 목록 페이지의 달성량 게이지 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feedTag/dto/FeedTagDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feedTag/entity/FeedTag.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/Controller.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/dto/TagDto.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/entity/Tag.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/mapper/TagMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/repository/TagRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/service/TagService.java

Entity
Dto
Controller
Repository
Service
Mapper
Issues : #18

[BE} Feat : Tag CRUD 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

1. Tag -Todo 연결
- POST, PATCH, RESPONSE Mapping Issues : #44

[BE] Feat: Tag Todo Mapping

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
server/routine/src/main/java/com/seb45_main_031/routine/feedTag/repository/FeedTagRepository.java

Tag와 Feed를 매핑했습니다.
_feedTag - FeedTagRepository 추가_

[BE] Feat : Tag - Feed Mapping

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

[BE] Add Todo 단일조회 기능 추가

---

FE/src/pages/TodoModifyPage.js

[FE] Feat : 할 일 수정 페이지 뷰 및 기능 구현

---

FE/src/components/Footer.js

- 작성하기 아이콘을 클릭 시 /todo/edit 페이지로 이동합니다.
- 할일목록 아이콘을 클릭 시 /todo/:today 페이지로 이동합니다.
Issues : #3

[FE] Fix : Footer 아이콘 클릭 시 페이지 이동 구현

---

FE/.eslintrc.json
FE/package-lock.json
FE/package.json
FE/src/pages/TodoModifyPage.js

:memo: axios 추가 install
:memo: hover 오류 수정
issue : #64

:bug: fix: .eslintrc.json_bug

---

server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/ReplyController.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/ReplyDto.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java

대댓글 기능 구현 완료했습니다.
생성 path : localhost:8080/comments/{parent-comment-id}/reply
추후 리팩토링 포인트 : DTO & Controller 하나로 병합
Issues : #60

[BE] Feat : 대댓글 기능 구현

---

FE/src/assets/icons/close.svg

#9 
- 혜란님 버셀 배포 테스트 중 이미지 파일 누락으로 에러 발생
- 모달창 닫기 버튼 아이콘 추가
N/A

[FE] Fix: 마이페이지 모달창 닫기 버튼 아이콘 추가

---

FE/src/data/constants.js
FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js
FE/src/pages/todoPage.js
FE/src/utils/getDateFormat.js

- 변수명 pascal > camel 로 변경
- 함수 선언 화살표 함수로 통일
- constants.js 파일로 상수 통합 관리
- utils 폴더로 유틸 파일 관리
- 컴포넌트명 단순화
- import 문 그룹핑
Issues : #74

[FE] 할 일 목록, 작성, 수정 파트 리팩토링

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

POST
content -> min, max 값 설정 - 한글 기준 바이트 -> 1 ~ 20 글자
date -> 현재와 미래 날짜만 허용
todoEmoji -> 디폴트 값 -> 운동 이모지 설정
tagId, memberId -> 메시지 설정
PATCH
date -> 유효한 날짜 범위 전부 허용
tag -> 메시지 설정
content -> min, max 값 설정 - 한글 기준 바이트 -> 1 ~ 20 글자
Issues: #76

[BE] Feat: TodoDto validation

---

FE/package-lock.json
FE/package.json
FE/src/App.js
FE/src/data/constants.js
FE/src/pages/CommunityEditPage.js
FE/src/pages/CommunityPage.js
FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js
FE/src/pages/todoPage.js

수정 사항이 있어 통합 풀 리퀘스트 보냅니다.
##
[할 일 목록 페이지]
- util getDateFormat 사용으로 코드를 변경하였습니다.
#6
##
[할 일 작성, 수정 페이지]
- 디폴트 이모지를 추가하였습니다.
- 유효성 검사를 추가하였습니다.
- 유효성 검사에 따른 결과를 모달로 표시합니다.
#8
##
[커뮤니티 목록 페이지]
- 멘토링 피드백 사항을 반영하여 코드를 개선하였습니다.
- 게시글 작성페이지로 이동 할 수 있는 버튼을 추가하였습니다.
#10
##
[커뮤니티 작성 페이지]
- 게시글 작성 페이지 뷰를 구현하였습니다.
- 구현 된 뷰는 다음과 같습니다. ( 타이틀, 작성TIP, 내 기록 불러오기, 태그, 게시글 에디터, 등록하기 버튼, 취소 버튼 )
- 게시글 작성 페이지 기능을 일부 구현하였습니다.
#11

[FE] 할 일 목록, 작성, 수정 페이지 및 커뮤니티 목록, 작성 페이지

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

Todo에 회원 검증 로직 추가
Todo에 tagId 값 가져오기(tagName 포함)
Issues: #61

[BE] :sparkles: Feat: Todo에 회원검증 로직 및 태그 ID값 가져오기

---

FE/src/components/Footer.js
FE/src/pages/CommunityPage.js
FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js
FE/src/utils/conutContentLength.js

[FE] 할 일 작성, 수정 / 커뮤니티 작성 이동 수정
다음과 같은 수정사항이 있습니다.
##
[할 일 작성, 수정]
- 게시글 작성 시 할 일 이름의 글자수를 확인 할 수 있습니다.
- 한글은 3byte 다른 문자는 1byte 로 계산 합니다.
- 글자수를 초과할 시 경고문과 에러 모달을 확인할 수 있습니다.
- 반복적으로 사용되는 함수를 util로 이동하였습니다.
#8 
##
[footer, 커뮤니티]
- 커뮤니티 게시판의 이동 버튼을 삭제하였습니다.
- footer의 이동 버튼의 path를 /community/edit 으로 수정하였습니다.
#10

[FE] 할 일 작성, 수정 / 커뮤니티 작성 이동 수정

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/dto/FeedLikeDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/entity/FeedLike.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/mapper/FeedLikeMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/repository/FeedLikeRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java

좋아요 기능 구현
- Entity
- Dto
- Controller
- Repository
- Service (♻️ : refactor)
- Mapper
- FeedLike 생성 / 기능 구현
Issues : #19

[BE] Feat : Like CRUD 기능 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/entity/Todo.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

할 일 여러 개 등록 API 추가
주석 추가 및 단일 조회 리팩토링
Issues: #91

[BE] Feat: Todo 할 일 여러 개 등록 API 추가

---

FE/src/data/dummy.js
FE/src/pages/MyPage.js

Issue #7
- `src/data/dummy.js` 더미 데이터에 멤버(id 6~8), 포스트(id6 게시글 3개) 추가
- 마이페이지에서 특정 사용자(id6 삐약이)의 게시물 조회하는 컴포넌트 추가
- 커뮤니티 페이지 FeedCard 컴포넌트 재사용
- 마이페이지 레이아웃 일부 수정(섹션 분류, 위치 조정), 세로 스크롤 추가
주요 기능 구현 후 이미지 파일 포함 디자인 수정 예정

[FE] Feat: 마이페이지 - 내 게시물 조회 컴포넌트 추가, 레이아웃 일부 수정

---

FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js

- 작성, 수정 페이지에서 스크롤이 생기지 않는 문제 해결
Issues : #8

[FE]  배포 시 화면이 덜 보이는 문제 해결

---

FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js
FE/src/pages/todoPage.js

- 할 일 목록, 작성, 수정 페이지의 api headers 에 accessToken 을 추가하였습니다.
Issues : #6 
Issues : #8

[FE] 할 일 페이지에 token 관련 추가

---

FE/src/components/Footer.js
FE/src/pages/LoginPage.js

- 유효성검사
- Link 스타일적용
- Footer Hover변경

[FE] Feat : LoginPage 유효성

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/mapper/FeedMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java

- dto
- entity
- mapper
- service
Issues : #99

[BE] Feed -> Todo Mapping

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java

Todo PostList 유효성 검사 애너테이션 추가
Issues: #101

[BE] Feat: Add todo valid

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java

- Valid 애너테이션 추가
Issues : #101

[BE] Feat: Add Feed valid

---

FE/src/pages/TodoEditPage.js
FE/src/pages/TodoModifyPage.js
FE/src/pages/todoPage.js
FE/src/utils/conutContentLength.js
FE/src/utils/countContentLength.js

- accessToken 의 유효기간으로 인해 생기는 문제 해결
- login 이 구현 될 시 삭제 예정
Issues : #6 #8

[FE] Token 관련 코드 수정

---

server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
server/routine/src/main/java/com/seb45_main_031/routine/member/repository/MemberRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java

memberId 검증 기능 추가
memberId 조회 기능 추가
nickname unique 적용
issuses : #110

[BE] Feat : Member 기능 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java

특정 Member가 작성한 Feed 조회 기능
Issues : #109

[BE] Feat : Member Feed 조회 기능

---

server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

[BE] Feat : Member exp/level 기능 추가

---

server/routine/build.gradle
server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/GlobalExceptionHandle.java
server/routine/src/main/java/com/seb45_main_031/routine/image/AwsS3Config.java
server/routine/src/main/java/com/seb45_main_031/routine/image/S3FileUploadService.java
server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
server/routine/src/main/resources/application.yml

AWS S3 이용 Member 이미지 업로드 기능 추가
이미지 업로드 관련 ExceptionCode 추가
이미지 업로드 관련 GlobalExceptionHandler 메소드 추가
Issues : #108

[BE] Feat : Member 이미지 업로드 기능

---

FE/src/pages/LoginPage.js
FE/src/pages/SignUpPage.js

- LoginPage, SignupPage 코드 간소화

[FE] Refactor: 멘토링 피드백 리팩토링

---

server/routine/src/main/java/com/seb45_main_031/routine/comment/controller/CommentController.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/service/CommentService.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/controller/FeedLikeController.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

COMMENT
FEED
FEEDLIKE
TODO
도메인 memberId 검증 로직 수정
Issues : #119

[BE] Fix : 각 도메인 memberId 검증 로직 수정

---

server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/controller/TodoStorageController.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/entity/TodoStorage.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/mapper/TodoStorageMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/repository/TodoStorageRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/service/TodoStorageService.java

Controller
Entity
Dto
Mapper
Service
Repository
Issues : #123

[BE] Feat : TodoStorage CRUD 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/controller/SavedTodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/entity/SavedTodo.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/repository/SavedTodoRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/service/SavedTodoService.java

Controller
Entity
Dto
Service
Repository
Issues : #124

[BE] Feat : SavedTodo CRUD 구현

---

server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java

member 액세스 토큰 유효성 검증 로직 변경으로 인한 @NotNull 애너테이션 삭제
Issues : #128

[BE] Refactor : 피드, 댓글 @NotNull 애너테이션 삭제

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/userDetailsService/CustomUserDetailsService.java

CustomUserDetailsService
CustomSuccessHandler
-> member 정보 추가
Issues : #131

[BE] Feat : 로그인 인증 MemberInfo 정보 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/filter/JwtVerificationFilter.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationEntryPoint.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/utils/ErrorResponder.java

서버에서 발급받지 않은 AccessToken 일 경우 -> 해당 예외 메시지 전달되도록 설정 
AccessToken 만료된 경우 -> 해당 예외 메시지 전달되도록 설정
Issuses : #135

[Be] Feat : AccessToken 검증 예외 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/entity/TodoStorage.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/mapper/TodoStorageMapper.java

TodoStorage 생성 시 -> savedTodo List 로 Post 할 수 있도록 설정 
savedTodo 생성 시 -> 항상 tagId 값을 넣도록 설정
Issues : #136

[BE] Feat : TodoStorage 기능 추가 및 SavedTodo 로직 변경

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/repository/TodoRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

PATCH 할 때 태그를 무조건 넣어줘야 했던 로직 선택 가능하게 수정
서비스 메서드 검증 로직을 위 쪽으로 넣어줘서 불필요한 서비스 로직 돌아가지 않게 코드 개선 
Issues: #134

[BE] Refactor: todo tag refactor

---

server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/mapper/SavedTodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

Todo PATCH Date 부분 삭제
savedTodo todoStorage 매핑

[BE] Remove: remove todo patch date & savedTodo mapping

---

FE/src/components/MyPageHeader.js
FE/src/pages/MyPageEdit.js

Issue #9
[Feat]
- 회원 탈퇴 모달창 input box 추가
- 비밀번호 일치할 경우 예 버튼 클릭 시 회원탈퇴 완료
- 에러 핸들링
[Design]
- 프론트 회의 결과 반영: 회원정보 수정 페이지 헤더 높이 조정 (95px -> 70px)
- 마이페이지 프로필 변경내용 저장버튼 위치 이동 (헤더 -> 프로필 편집 섹션)
- 프로필 편집 섹션 컴포넌트 margin 값 조정
- 서버 재배포에 따른 테스트 코드 수정
- 추후 스타일링, 리팩토링 진행하도록 하겠습니다.

[FE] Feat & Design: 마이페이지 회원탈퇴 기능 구현, 헤더 및 컴포넌트 크기 조정

---

server/routine/build.gradle
server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/userDetailsService/CustomUserDetailsService.java
server/routine/src/main/java/com/seb45_main_031/routine/member/entity/Member.java
server/routine/src/main/java/com/seb45_main_031/routine/member/repository/MemberRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
server/routine/src/main/resources/application.yml

Google OAuth2 로그인 구현
Member SignupType 컬럼 추가
Issues : #151

[BE] Feat : OAuth2 구현

---

FE/src/pages/MyPage.js
FE/src/pages/MyPageEdit.js

Issue #7 #9 마이페이지 - 로그인, 회원가입 기능 구현 완료에 따른 코드 수정
- 테스트 코드 삭제
- 닉네임 변경 에러 핸들링 추가
- 미구현 advanced 기능(프로필 사진 변경) 안내 alert 추가

[FE] Feat: 마이페이지 로그인, 회원가입 기능 연결

---

FE/src/pages/LoginPage.js

[FE] Feat: LoginPage Alert 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/comment/dto/CommentDto.java
server/routine/src/main/java/com/seb45_main_031/routine/comment/entity/Comment.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/controller/FeedController.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/dto/FeedDto.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/repository/FeedRepository.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/service/FeedService.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java

- Feed, Comment 유효성 검사 로직 추가
- FeedService에서 필요하지 않은 메서드 삭제
- 피드 리스트 조회시 @RequestParam에서 default 해제
Issues : #101

[BE] Feed, Comment 유효성 검증

---

server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/TagController.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/dto/TagDto.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/entity/Tag.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/mapper/TagMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/service/TagService.java
server/routine/src/main/resources/application.yml

dto / mapper / controller / service -> 관련 내용 추가
Tag entity -> tagName -> unique 설정
TagName 중복 관련 Exception Code 추가
Issues : #161

[BE] Feat : Tag Patch 기능 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/dto/TodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/service/TodoService.java

Todo 완료여부 미래 날짜 적용 불가로 수정
Todo Response memberId, level 추가

[BE] todo complete refactor & Add memberId, level

---

FE/src/pages/LoginPage.js
FE/src/pages/SignUpPage.js

[FE] Fix: Login Signup 유효성검사

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/ErrorResponse.java
server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java
server/routine/src/main/java/com/seb45_main_031/routine/todoStorage/dto/TodoStorageDto.java

Member Dto 유효성 검증 추가
SavedTodo Dto 유효성 검증 추가
TodoStorage Dto 유효성 검증 추가
Issues : #170

[BE] Feat : 유효성 검증 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/savedTodo/dto/SavedTodoDto.java

Member Dto 유효성 검증 추가
SavedTodo Dto 유효성 검증 추가
TodoStorage Dto 유효성 검증 추가
Issues : #170

Feat : Member 유효성 검증 추가

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/CustomAuthenticationSuccessHandler.java
server/routine/src/main/java/com/seb45_main_031/routine/exception/ExceptionCode.java
server/routine/src/main/java/com/seb45_main_031/routine/feed/entity/Feed.java
server/routine/src/main/java/com/seb45_main_031/routine/feedLike/service/FeedLikeService.java

- 낙관적 락 (Optimistic Lock) 적용
Issues : #157

[BE] 피드 좋아요 기능에 대한 동시성 문제

---

FE/src/pages/SignUpPage.js

[FE] Fix: 비밀번호 유효성 수정

---

server/routine/src/main/java/com/seb45_main_031/routine/todo/controller/TodoController.java
server/routine/src/main/java/com/seb45_main_031/routine/todo/mapper/TodoMapper.java

Todo memberId, level 정보 수정
Issues: #181

[BE] Fix: todo refactor member id level

---

FE/src/pages/CommunityModifyPage.js
FE/src/pages/LoginPage.js
FE/src/pages/MyPage.js
FE/src/pages/MyPageEdit.js
FE/src/pages/SignUpPage.js
FE/src/utils/authLoginCheck.js

- localStorage에 token이 있지만 유효하지 않을 경우 계속해서 replace가 발생하는 오류 해결

[FE] 필요 없는 코드 삭제 및 오류 해결

---

FE/src/pages/MyPageEdit.js

Issue #196
- 닉네임 필수값
- 최대 10글자
- 닉네임 앞, 뒤, 중간 공백 포함 불가

[FE] Feat: 닉네임 유효성 검사

---

FE/src/pages/MyPage.js

Issue #196 
문제점: 웹뷰에 따라 마이페이지 전체가 보이지 않아 로그아웃 버튼을 찾기 위해 사용자가 화면 축소를 해야함
-- 해결: 스크롤(overflow) 구현하였으나 해당 컨테이너 height값 때문에 적용이 안 되어 수정함
스타일드 컴포넌트 일부 수정 (bg color)

[FE] Design: 마이페이지 스크롤 추가

---

FE/src/pages/MyPageEdit.js

Issue#196
닉네임 유효성검사 수정
- 닉네임 최소 2글자 이상 추가 -> 닉네임 최소 2글자 이상, 최대 10글자
닉네임 유효성 검사 최종
1. 닉네임 필수값
2. 닉네임 최소 2글자 이상, 최대 10글자
3. 닉네임 앞, 뒤, 중간 공백 불가

[FE] Fix: 닉네임 유효성검사 수정

---

server/routine/build.gradle
server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java
server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
server/routine/src/main/resources/application.yml

Google OAuth2 수정
member 전체조회 삭제
yml 설정
Issues : #200

[BE] :recycle: Refactoring : OAuth2 수정 / member 전체조회 삭제 / yml 설정

---

FE/src/pages/MyPageEdit.js

Issue #196
백엔드 API 수정 관련 닉네임 변경 로직 수정

[FE] Fix: 닉네임 변경 로직 수정

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/handler/OAuth2LoginSuccessHandler.java

Google OAuth2 로그인 시 중복되는 닉네임이 있을 경우
닉네임에 4자리 랜덤 숫자가 추가되도록 설정
Issues : #207

[BE] Modify : Google OAuth2 중복이름 변경

---

server/routine/src/main/java/com/seb45_main_031/routine/auth/config/SecurityConfiguration.java
server/routine/src/main/java/com/seb45_main_031/routine/member/controller/MemberController.java
server/routine/src/main/java/com/seb45_main_031/routine/member/dto/MemberDto.java
server/routine/src/main/java/com/seb45_main_031/routine/member/mapper/MemberMapper.java
server/routine/src/main/java/com/seb45_main_031/routine/member/service/MemberService.java
server/routine/src/main/java/com/seb45_main_031/routine/tag/controller/TagController.java

- 이미지 등록시 -> memberId / 이미지 url -> response 로 주도록 설정 
- 이미지 등록 핸들러 -> @RequestParam -> @RequestPart 로 변경
- Spring Security Configuration 권한 설정 -> Member 쪽 ADMIN 설정 삭제 
- Tag delete 핸들러 -> deleteTag 로 이름 수정
- Issues : #209

[BE] Modify : Member 이미지 관련 변경 사항

---

FE/src/data/constants.js
FE/src/pages/GooglePage.js
FE/src/pages/LoginPage.js

- google oauth의 코드를 일부 수정하였습니다.
- URL 상수의 값을 수정하였습니다.
- google oauth 연결 path 값을 수정하였습니다.
Issues : #190

[FE] Fix : oauth 수정 및 url 주소 변경
